
name: build

on:
  push:
    tags: ['v*']
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build # SonarScan locks some files and breaks Build if done first
      run: |
        dotnet publish -r osx-x64 -p:PublishSingleFile=true --self-contained Eto.Microcharts.Demo
        dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained Eto.Microcharts.Demo
        # wrap artifacts in tar archives to maintain permissions intact
        tar --directory=Eto.Microcharts.Demo/bin/Mac64/Debug/net6.0/osx-x64/publish -cvf Eto.Microcharts.Demo.Mac.tar Eto.Microcharts.Demo.app
        tar --directory=Eto.Microcharts.Demo/bin/Gtk/Debug/net6.0/linux-x64/publish -cvf Eto.Microcharts.Demo.Gtk.tar Eto.Microcharts.Demo

    - name: SonarScanner # for .NET 6 with pull request decoration support
      uses: highbyte/sonarscan-dotnet@v2.1.2
      with:
        sonarProjectKey: rafntor_Eto.Microcharts
        sonarProjectName: Eto.Microcharts
        sonarOrganization: rafntor
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Upload Eto.Microcharts.Mac artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Eto.Microcharts.Demo.Mac
        path: Eto.Microcharts.Demo.Mac.tar

    - name: Upload Eto.Microcharts.Gtk artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Eto.Microcharts.Demo.Gtk
        path: Eto.Microcharts.Demo.Gtk.tar

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: |
        dotnet build -c Release Eto.Microcharts
        dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained Eto.Microcharts.Demo
    
    - name: Upload TestApp.Wpf artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Eto.Microcharts.Demo.Wpf
        path: Eto.Microcharts.Demo/bin/Wpf/Debug/net6.0-windows/win-x64/publish/Eto.Microcharts.Demo.exe

    - name: Upload nuget artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nuget
        path: Eto.Microcharts/bin/Release/*.nupkg

    - name: Push to nuget.org
      if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
      run: dotnet nuget push '.\Eto.Microcharts\bin\Release\*.nupkg' --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
